get https://localhost:8000/api/transport_orders/102
Content-Type: application/json

{
    "carrier": "/api/carriers/2",
    "vehicle": "/api/vehicles/1",
    "firstLoadingWarehouse": "/api/warehouses/2",
    "firstLoadingStart": "2020-07-17T12:32:00+00:00",
    "firstDeliveryWarehouse": "/api/warehouses/2",
    "firstLoadingEnd": "2020-07-18T12:32:00+00:00",
    "firstDelivery": "2020-07-19T12:32:00+00:00",
    "amount": 1235
}
