easy_admin:
  design:
    brand_color: 'black'
    menu:
      - { label: 'Retour au planning', icon: 'sign-in', route: 'app' }
      - label: 'Information transport'
        children:
          - {entity: 'Warehouse', icon: 'industry', label: 'Entrepôts'}
          - {entity: 'Carrier', icon: 'truck-moving', label: 'Transporteurs'}
          - {entity: 'Adress', icon: 'address-card', label: 'Adresses'}
      - label: 'Paramètrage transport'
        children:  
          - {entity: 'Country', icon: 'globe', label: 'Pays'}
          - {entity: 'Vehicle', icon: 'truck-moving', label: 'Véhicules'}
      - label: 'Tarifs'
        children:  
          - {entity: 'Rate', icon: 'euro-sign', label: 'Tarif'}  
      - label: 'Réglage global'
        children:          
          - {entity: 'InitialParams', icon: 'tools', label: 'Paramètres de base'}
          - {entity: 'DestinationParams', icon: 'tools', label: 'Paramètres de destination'}
      - label: 'Profils'
        children:
            - {entity: 'User', icon: 'user', label: 'Utilisateur'}  