easy_admin:
  design:
    brand_color: 'black'
    menu:
      - label: 'Parametrage'
        icon: 'tools'
        children:
          - {entity: 'Warehouse', icon: 'industry', label: 'Entrepôts'}
          - {entity: 'Carrier', icon: 'truck-moving', label: 'Transporteurs'}
          - {entity: 'Country', icon: 'globe', label: 'Pays'}
          - {entity: 'Adress', icon: 'address-card', label: 'Adresses'}
          - {entity: 'Vehicle', icon: 'truck-moving', label: 'Véhicules'}