easy_admin:
  entities:
    Rate:
        class: App\Entity\Rate
        label: 'Tarif'
        list:
          fields:
            - { property: 'carrier', label: 'Transporteur' } 
            - { property: 'firstLoadingWarehouse', label: 'Lieu de chargement 1'}
            - { property: 'secondLoadingWarehouse', label: 'Lieu de chargement 2'}
            - { property: 'firstDeliveryWarehouse', label: 'Lieu de livraison 1'}
            - { property: 'secondDeliveryWarehouse', label: 'Lieu de livraison 2'}
            - { property: 'amount', label: 'Tarif'}
        form:
          fields:
            - { property: 'carrier', label: 'Transporteur' } 
            - { property: 'firstLoadingWarehouse', label: 'Lieu de chargement 1'}
            - { property: 'secondLoadingWarehouse', label: 'Lieu de chargement 2'}
            - { property: 'firstDeliveryWarehouse', label: 'Lieu de livraison 1'}
            - { property: 'secondDeliveryWarehouse', label: 'Lieu de livraison 2'}
            - { property: 'amount', label: 'Tarif'}       