easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'Utilisateur'
      list:
        fields:
          - { property: 'email', label: 'Adresse email' } 
          - { property: 'roles', label: 'Rôles', type: json_array }
      form:
        fields:
            - { property: 'email', label: 'Adresse email' } 
            - { property: plainPassword, label: 'mot de passe', type: 'password' }
            - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}