easy_admin:
  entities:
    Vehicle:
      class: App\Entity\Vehicle
      list:
        fields:
          - { property: 'name', label: 'Nom' } 
      form:
        fields:
            - { property: 'name', label: 'Nom' } 